INSERT INTO tb_brand(name) VALUES ('Chevrolet');
INSERT INTO tb_brand(name) VALUES ('Ford');
INSERT INTO tb_brand(name) VALUES ('Fiat');
INSERT INTO tb_brand(name) VALUES ('Volkswagen');
INSERT INTO tb_brand(name) VALUES ('BYD');
INSERT INTO tb_brand(name) VALUES ('Audi');
INSERT INTO tb_brand(name) VALUES ('BMW');
INSERT INTO tb_brand(name) VALUES ('Honda');
INSERT INTO tb_brand(name) VALUES ('Hyundai');
INSERT INTO tb_brand(name) VALUES ('Jeep');
INSERT INTO tb_brand(name) VALUES ('Nissan');
INSERT INTO tb_brand(name) VALUES ('Peugeot');
INSERT INTO tb_brand(name) VALUES ('Renault');
INSERT INTO tb_brand(name) VALUES ('Toyota');
INSERT INTO tb_brand(name) VALUES ('Mercedes-Benz');
INSERT INTO tb_brand(name) VALUES ('Land Rover');
INSERT INTO tb_brand(name) VALUES ('Mitsubishi');
INSERT INTO tb_brand(name) VALUES ('Chery');
INSERT INTO tb_brand(name) VALUES ('Citroën');
INSERT INTO tb_brand(name) VALUES ('Ram');
INSERT INTO tb_brand(name) VALUES ('Volvo');
INSERT INTO tb_brand(name) VALUES ('Kia');
INSERT INTO tb_brand(name) VALUES ('Porsche');
INSERT INTO tb_brand(name) VALUES ('Ferrari');

